#!/bin/bash
# Append or replace Facebook Page vars in backend/.env (run on VPS).
set -euo pipefail
ENV_FILE="${1:-/var/www/hinyerevan/backend/.env}"

: "${FACEBOOK_APP_ID:?FACEBOOK_APP_ID required}"
FACEBOOK_PLUGIN_APP_ID="${FACEBOOK_PLUGIN_APP_ID:-802992039416856}"
: "${FACEBOOK_PAGE_ID:?FACEBOOK_PAGE_ID required}"
: "${FACEBOOK_PAGE_URL:?FACEBOOK_PAGE_URL required}"
: "${FACEBOOK_PAGE_ACCESS_TOKEN:?FACEBOOK_PAGE_ACCESS_TOKEN required}"

tmp="$(mktemp)"
grep -v -E '^FACEBOOK_APP_ID=|^FACEBOOK_APP_SECRET=|^FACEBOOK_PLUGIN_APP_ID=|^FACEBOOK_PAGE_ID=|^FACEBOOK_PAGE_URL=|^FACEBOOK_PAGE_ACCESS_TOKEN=' "$ENV_FILE" >"$tmp" || true
cat "$tmp" >"$ENV_FILE"
{
  echo "FACEBOOK_APP_ID=${FACEBOOK_APP_ID}"
  echo "FACEBOOK_PLUGIN_APP_ID=${FACEBOOK_PLUGIN_APP_ID}"
  [ -n "${FACEBOOK_APP_SECRET:-}" ] && echo "FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}"
  echo "FACEBOOK_PAGE_ID=${FACEBOOK_PAGE_ID}"
  echo "FACEBOOK_PAGE_URL=${FACEBOOK_PAGE_URL}"
  echo "FACEBOOK_PAGE_ACCESS_TOKEN=${FACEBOOK_PAGE_ACCESS_TOKEN}"
} >>"$ENV_FILE"
rm -f "$tmp"
echo "Updated Facebook Page vars in $ENV_FILE"
